### ISSUE TITLE
Setting `SERVICE_BINDING_ROOT` does not apply at detect

### ISSUE THREAD

**Issue by dmikusa-pivotal** [buildpacks/libcnb#105]
If you set an alternative location for `SERVICE_BINDING_ROOT` this only presently applies at build time. At detect, the standard `/platform/bindings` is always used.

Detect calls [NewBindingsFromPath](https://github.com/buildpacks/libcnb/blob/main/detect.go#L129-L134) which is given `/platform/bindings`. This method does not look at EnvServiceBindings, so it doesn't honor this env variable.

**Comment by samj1912** [comment]
@dmikusa-pivotal thanks for the report! Will roll out a fix shortly
