### ISSUE TITLE
Provide a path for integration tests

### ISSUE THREAD

**Issue by dmikusa** [buildpacks/libcnb#259]
Split from #53.

We should consider adding utilities for integration testing buildpacks (possibly in a separate library) that possibly uses pack and docker. Example of something like this https://github.com/paketo-buildpacks/occam

Alternatively, we could endorse using `occam` and update docs to reflect this.

**Comment by loewenstein** [comment]
> Alternatively, we could endorse using occam and update docs to reflect this.

We really should **not** reinvent occam. Either use it from where it currently lives or approach the occam maintainers if they could see moving into the cnb project.

**Comment by dmikusa** [comment]
This hasn't received any positive feedback or interest, so I'm going to close this and suggest that if folks are looking for a way to do integration testing, then they should take a look at https://github.com/paketo-buildpacks/occam.
