### ISSUE TITLE
Release of `v2`

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [buildpacks/libcnb#302]
A `v2` is in the making for roughly a year (?) now, we should clarify what is still missing and finally release a `v2.0.0`. I see several reasons for that:

1. Workaround like [this](https://github.com/paketo-buildpacks/procfile/issues/246) are discussed and evaluated which would not be necessary with `v2`
2. It would the buildpack using `libpak` to implement *BUILDPACK API 0.9* which is nearly 2 years old
3. Downstream projects like `libpak` could release as well
4. There is a risk with having such long living branches (`main` vs. `release 1.x`), since it is easier for some regression to slip through over time. I think the double maintenance should be limited.

**Comment by dmikusa** [comment]
I'm going to be cutting an v2.0.0 RC1 release very soon (hopefully today). If folks could test and provide feedback, that would be very helpful.

Also, feedback on https://github.com/buildpacks/libcnb/blob/main/MIGRATION-v1-to-v2.md would be helpful also.

**Comment by dmikusa** [comment]
RC1 https://github.com/buildpacks/libcnb/releases/tag/v2.0.0-rc.1 has been release.

Please give it a try and report any issues. If all goes well and there are no issues, we can cut a release towards the end of this month. Maybe Oct 21st, that's about two weeks for folks to give this a spin.

Thanks

**Comment by dmikusa** [comment]
We got no feedback positive or negative on RC1, so I've proceeded with the release.

https://github.com/buildpacks/libcnb/releases/tag/v2.0.0

2.0.0 is available now 🥳
