### ISSUE TITLE
libcnb feedback - layer contributors

### ISSUE THREAD

**Issue by samj1912** [buildpacks/libcnb#49]
The following was discussed in the WG office hours on 25/03/2021 (https://www.youtube.com/watch?v=1hjN6FVH2Vs&t=2234s) and below is a summary of the discussion.

Having used libcnb for quite a few buildpacks, I have noticed some issues with the current interface that make it difficult to implement certain kinds of buildpacks. Some issues are as follows - 

## Restrictive API

Currently libcnb exposes LayerContributors as a interface for creating new layers. The interface accepts a layer and outputs a layer. A common part of layer creation process may be updating things like the BOM, dynamically creating labels, processes, slices, unmet dependencies or the persistent metadata. Although it is possible to update things like BOM as a part of the contribution process since it is a pointer, the same cannot be said for the other things that I mentioned above.

## Encapsulation 

Even for updating the BOM, it requires knowledge about how the build process in libcnb works internally. Otherwise you may not know when the layer contribution occurs v.s when the bom is written in order to correctly update it in the right place. This breaks the encapsulation that the builder interface is supposed to provide

## Hacky alternatives

Although the above could technically be done in the builder process, it is hard to do it at same time as the layer generation process, unless you hack your way around it by generating the layer manually in the builder and returning some dummy layer contributors with the same name as the generated layers so that the build process doesn't clean them up.

### Alternative 1
packit is another popular alternative to libcnb that offers a simpler interface to creating layers. 

https://github.com/paketo-buildpacks/packit/blob/7809aeb5fe7a87dfcbda4fa8b5738427d71df4d3/build.go#L187
https://github.com/paketo-buildpacks/packit/blob/7809aeb5fe7a87dfcbda4fa8b5738427d71df4d3/layers.go#L21
https://github.com/paketo-buildpacks/packit/blob/main/layer.go

which solves most of the above mentioned problems.

We could change the layer contributor interface to something similar to above

### Alternative 2

Modify the layer contributor to be able to modify all of the above parts of the build result as an obvious part of its api. This might mean that all things that are not pointers (processes, slices etc) need to be converted to one and we should have some examples on how to modify this as a part of the layer contribution process in the docs for libcnb.

**Comment by samj1912** [comment]
I tried to address some of these issues in a python version of libcnb that I wrote. You can see the relevant documentation at https://samj1912.github.io/python-libcnb/

**Comment by dmikusa-pivotal** [comment]
Hi, this is Dan, I started working with @ekcasey on several projects recently including libcnb and libpak. She asked me to take a look at this issue. If there are pain points in the API, I'd definitely like to talk more about them and see what we can do to improve things.

>Currently libcnb exposes LayerContributors as a interface for creating new layers. The interface accepts a layer and outputs a layer. A common part of layer creation process may be updating things like the BOM, dynamically creating labels, processes, slices, unmet dependencies or the persistent metadata. Although it is possible to update things like BOM as a part of the contribution process since it is a pointer, the same cannot be said for the other things that I mentioned above.

Do you have any examples that you can share? Public buildpacks you could link me to or code snippets? I think it might help to talk about something concrete where the API is problematic. Then we could explore what would make that easier. 

>Although the above could technically be done in the builder process, it is hard to do it at same time as the layer generation process,

I'd also like to know more about this. 

I was looking through a handful of the buildpack that our team has written and they are basically all manipulating the items you mentioned in the builder method, and what happens in the LayerContributor seems to be separated so that its focus is primarily on file and layer metadata manipulation or where we shell out and run external commands that do (i.e. things that directly modify the layer). 

I'm not saying there's a right or wrong answer, I'm just curious how you're breaking things down in your buildpacks and why you prefer to move some of what is happening into the LayerCreator vs doing it in the builder.

**Comment by samj1912** [comment]
Hi Dan, 

Thanks for taking a look at this issue. Here's a simple example - 

> Do you have any examples that you can share? Public buildpacks you could link me to or code snippets? I think it might help to talk about something concrete where the API is problematic. Then we could explore what would make that easier.


I wish to do something as simple as the follows - 

You have a list of python dependencies in a `requirements.txt` and you wish to do the following - 

Install the python dependencies listed in requirements.txt using `pip install -r requirements.txt` to a layer and also take the final list of dependencies that have been installed (since these dependencies may have their own dependencies that are not listed in the original requirements.txt file) and put them in a BOM. You can do this by running `pip freeze` pointing the layer where these dependencies where installed.

Doing this involves creating a layer contributor that takes in the BOM pointer and updates it during the layer contribution process.
Now if the BOM export were to happen BEFORE the layer contribution happens, the modifications made by the layer contributor would never be reflected. The fact that we have to know the order of these operations as they are implemented in libcnb even though all we should be doing is providing an output build result is one cause for concern. But this is still possible. Let's take about the next case.

Now let's say you want to set a label on the final image based on whether or not a certain package was installed. For eg

label with  key = mypackage-instaled, value=true.

Now the above value of the label can only be determined based on what was installed on the layer or not and then checking the output packages in the layer, again using pip freeze. Now given that labels are a slice and not a pointer to a slice I can modify them as a part of the layer contribution process. So now we are left in a situation where we have to set a label before the layer contributor can actually do the contribution process but we can only know the value of the label after the contribution has happen.

Doing the above with the current API can be very convoluted as the layer contribution happens after the build process.

To do this you would have to do something like this - 

use context.Layers.Get to get the layer and run all these above operations to install the packages in the layer and set the label in the build process instead of a layer contributor. And then create a dummy layer contributor with the same name as this layer which does nothing in the contribution process except set the metadata as all the other layers which are not represented as layer contributors are not exported as their layer tomls are deleted https://github.com/buildpacks/libcnb/blob/478b9311b1de0f100367f19d6bca69965c619d00/build.go#L283-L294


I can go into more details in the next office hours meeting or we can continue on slack if it helps :)

**Comment by dmikusa-pivotal** [comment]
No, that makes sense and I can see where it's causing pain. I was looking in the maven repo & libbs that we use in Paketo and those are doing the same with the BOM. The pointer is passed into the LayerContributor and modified just like you're doing.

Let's chat more about how we can improve things on Slack.

**Comment by samj1912** [comment]
Fixed in #74
