### ISSUE TITLE
Add docs and examples for usage 

### ISSUE THREAD

**Issue by samj1912** [buildpacks/libcnb#50]
Currently the documentation on libcnb is a bit lacking when it comes to usage. We should add some examples on how to use the various apis/ utilities available in libcnb with a simple buildpack.

Examples of what I am expecting from the resolution of this issue -

https://github.com/paketo-buildpacks/packit#buildpack-interface

https://github.com/Malax/libcnb#example-buildpack

We could also consider adding a buildpack to the samples repository that uses libcnb.

**Comment by AidanDelaney** [comment]
Please assign to me.

**Comment by AidanDelaney** [comment]
We need a concrete example here.  I'm going to provide example `detect` and `build` sources for a `pip install` buildpack.  We will assume the existence of a `python-dist` buildpack that provides a runtime and a `pip-dist` buildpack that provides the `pip` binary.  In our simplified scenario `requirements.txt` can contain only package names and comment lines.  This scenario is similar to the simplified NodeJS scenario used in the packit documenteation.

Is this scenario both simple enough to understand and complex enough to demonstrate the basics of `libcnb`?

**Comment by dmikusa-pivotal** [comment]
I think it would be nice to have an example that's self-contained. Having the assumed existence of other buildpacks, IMHO, makes it harder to follow & ultimately test. Unless you are going to actually use an existing buildpack for those like Paketo. That does make examples harder.

Taking a step back, thinking about the types of things I'd like to see in a demo:

- Detection
  - how to discover basic things like app location, buildpack location, etc..
  - Detection pass/fail
  - providing/requiring items in the buildplan
  - looking at bindings

- Build
  - Common locations at build (very similar to detect) & finding binding info
  - Looking at the buildplan
  - Failing a build
  - Logging/Writing messages to a user
  - Layers (creating, writing files to them, layer flags)
  - Setting labels, process types, slices and exec.d helpers

- Packaging up the buildpack
  - This is important cause you need to compile the Go code & run `pack buildpack package` against the compiled code.
  - That said, I'm not sure what to suggest. We have a system for this, which is being used with the profile buildpack but is undoubtedly more complicated than necessary. Probably, just need a basic Makefile we can suggest with some commands to test, compile & package.

I'm not sure there will be a legitimate sample buildpack that uses all that stuff, but an idea might be to branch off in a section, show one of the features like slices, say "here's how we could add a slice", but then backtrack to the main example and explain that's not necessary to add slices in this example.

Maybe you could apply a little magic too and have a buildpack that uses stuff from the builder image. We could have a custom samples builder, perhaps with Python in it or you could do a C/C++ buildpack that uses the built-in compiler tool? Then add a disclaimer to the tutorial explaining that's not best practice to use stuff from the builder, but it's being done here to make the example easier to follow.

**Comment by samj1912** [comment]
Fixed in #164
