### ISSUE TITLE
Setting `SERVICE_BINDING_ROOT` does not at build time

### ISSUE THREAD

**Issue by dmikusa-pivotal** [buildpacks/libcnb#55]
When you run a container created by buildpacks, you may set an env variable `SERVICE_BINDING_ROOT` to instruct where to find bindings. This request is to support the same at build time.

Presently if you pass `--env SERVICE_BINDING_ROOT` to `pack build` (or similar tools) for libcnb based buildpacks, the value is ignored and it requires you to locate your bindings under `/platform/bindings` or they are ignored.

**Comment by samj1912** [comment]
As a part of this - I think we should also update the buildpack extension spec for service bindings. Currently the spec points to https://github.com/buildpacks/spec/blob/main/extensions/bindings.md#detect-and-build-phases ($PLATFORM_PATH/bindings)

(I know we currently support the k8s binding spec during runtime https://github.com/k8s-service-bindings/spec but I don't think we actually have it documented in the official buildpack spec anywhere)

I believe the builder spec that is up and coming has this defined more officially - https://github.com/buildpacks/spec/pull/193/files
