### ISSUE TITLE
Add RELEASE.md for creating cutting a new release

### ISSUE THREAD

**Issue by hone** [buildpacks/libcnb#60]
Match other buildpacks repos to have release documentation

**Comment by Phantsure** [comment]
Wanted to make this, could you guide me through?

I didn't find any code on how to release code but I think it should be similar to https://github.com/buildpacks/lifecycle/blob/main/RELEASE.md . Please could you validate and point me to any libcnb specific changes that might be required?

**Comment by dmikusa-pivotal** [comment]
I'm not totally sure I follow your question @Phantsure. As an end-user, you wouldn't make anything here. That would be done by project maintainers. We publish releases [here](https://github.com/buildpacks/libcnb/releases).

This project is a Go library, so you would simply include it into your project with `go get`, go modules, or however you prefer to add Go libraries into your projects.

An example of consuming this can be seen [here](https://github.com/paketo-buildpacks/jmx/blob/main/go.mod#L6) and [here](https://github.com/paketo-buildpacks/jmx/blob/main/jmx/build.go#L22).

**Comment by samj1912** [comment]
the libcnb release process is actually fairly trivial. On each push to `main` a draft release is updated with the appropriate version number and notes. When we want to cut a release we simply need to go to the Github UI and mark a release as final.

**Comment by Phantsure** [comment]
Thank you @samj1912 got similar idea reading from action workflows and reading release.md of lifecycle.
@dmikusa-pivotal Okay got that. I just wanted to contribute to buildpacks and found this issue as a good starting point. 
I will leave this issue if changes needed are to be done by a maintainer. :)

**Comment by dmikusa-pivotal** [comment]
Gotcha. @Phantsure If you are looking to help with docs, we have a number of issues open [here](https://github.com/buildpacks/docs/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fbuildpack-authors-tooling). If you want to chat about any you can also join our Slack, if you haven't already. Happy to help facilitate contributions where I can.

**Comment by samj1912** [comment]
Closing this as our current release process is fairly straight-forward.
