### ISSUE TITLE
libcnb v2: Rename poet to logging

### ISSUE THREAD

**Issue by dmikusa-pivotal** [buildpacks/libcnb#81]
Right now libcnb uses the package name of `poet` for its logging package.

https://github.com/buildpacks/libcnb/tree/main/poet

We should rename this to something more boring and straightforward so that it's easier to see what the package does and more accessible for non-native English speakers.

Presently you would use the library in a manner like this:

```
logger := poet.NewLogger(os.Stdout)
```

given this, other options would be:

1. `logger := logging.NewLogger(os.Stdout)`
2. `logger := log.NewLogger(os.Stdout)`
3. `logger := logs.NewLogger(os.Stdout)`

Please add your thoughts on these options below or other suggestions for package names.

**Comment by dmikusa-pivotal** [comment]
I'm not seeing any comments/objects, so I will go ahead and submit a PR for this shortly.

**Comment by samj1912** [comment]
Resolved by #89
